// Stable cache key for a custom address derived from its (lat, lng).
//
// Used by:
//   • /api/clean-image  → public/cache/houses/{key}/clean.png
//   • /api/trellis      → public/cache/houses/{key}/model.glb
//   • /api/design       → public/baked/{key}-analysis.json
//                         (generated by fetchAndAnalyzeLive)
//
// 6-decimal precision = ~10 cm. Two requests for the same physical
// address always hash to the same key even if Google Places sends
// trace-level rounding noise. Replacing "." with "_" keeps the key
// usable as a directory name on every filesystem.

export function liveCacheKey(lat: number, lng: number): string {
  return `live-${lat.toFixed(6).replace('.', '_')}-${lng.toFixed(6).replace('.', '_')}`;
}
