// House loader — OWNED by Dev A
// Loads the STYLIZED low-poly model generated by Dev D from 3D Tiles photogrammetry.
// The raw 3D Tiles mesh is used OFFLINE for analysis only — never rendered to user.
//
// Pipeline:
//   3D Tiles (Google)  →  fetch-3d-tiles.ts (Dev D, offline)  →  photogrammetry.glb
//                      →  analyze-roof.ts (Dev D, offline)    →  analysis.json (faces, obstructions, panel positions)
//                      →  generate-stylized.ts (Dev D)        →  stylized.glb  ← we display this
//
// Until Dev D delivers stylized.glb, fall back to a procedural placeholder.

'use client';

import { useGLTF } from '@react-three/drei';
import { Suspense, useState, useEffect } from 'react';
import type { HouseId } from '@/lib/types';

const STYLIZED_PATHS: Record<HouseId, string> = {
  brandenburg: '/baked/brandenburg-stylized.glb',
  hamburg: '/baked/hamburg-stylized.glb',
  ruhr: '/baked/ruhr-stylized.glb',
};

interface Props {
  houseId: HouseId;
}

export function House({ houseId }: Props) {
  const [glbExists, setGlbExists] = useState<boolean | null>(null);

  useEffect(() => {
    fetch(STYLIZED_PATHS[houseId], { method: 'HEAD' })
      .then((r) => setGlbExists(r.ok))
      .catch(() => setGlbExists(false));
  }, [houseId]);

  if (glbExists === null) return null;
  if (glbExists) {
    return (
      <Suspense fallback={null}>
        <StylizedGLB houseId={houseId} />
      </Suspense>
    );
  }
  return <ProceduralPlaceholder />;
}

function StylizedGLB({ houseId }: { houseId: HouseId }) {
  const { scene } = useGLTF(STYLIZED_PATHS[houseId]);
  return <primitive object={scene} />;
}

// Fallback procedural house — cel-shaded white volume with a tilted roof.
// Used until Dev D commits stylized.glb. Keeps Dev A unblocked from Sat 15:00.
function ProceduralPlaceholder() {
  return (
    <group>
      {/* Base block */}
      <mesh position={[0, 1.5, 0]} castShadow receiveShadow>
        <boxGeometry args={[7, 3, 5]} />
        <meshToonMaterial color="#f5f1ea" />
      </mesh>
      {/* Hip roof — front face (SSW, 195°, 35°) */}
      <mesh position={[0, 4.2, 0]} rotation={[0.6, 0, 0]} castShadow>
        <planeGeometry args={[7.5, 3]} />
        <meshToonMaterial color="#c14a3a" side={2} />
      </mesh>
      {/* Hip roof — back face */}
      <mesh position={[0, 4.2, 0]} rotation={[-0.6, 0, 0]} castShadow>
        <planeGeometry args={[7.5, 3]} />
        <meshToonMaterial color="#c14a3a" side={2} />
      </mesh>
      {/* Chimney */}
      <mesh position={[2.2, 5.4, -0.5]} castShadow>
        <boxGeometry args={[0.4, 1.2, 0.4]} />
        <meshToonMaterial color="#8b5e3c" />
      </mesh>
      {/* Ground plane */}
      <mesh position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} receiveShadow>
        <planeGeometry args={[40, 40]} />
        <meshToonMaterial color="#e8e8e8" />
      </mesh>
    </group>
  );
}

// Preload stylized GLBs (no-op if files don't exist yet)
Object.values(STYLIZED_PATHS).forEach((p) => {
  try {
    useGLTF.preload(p);
  } catch {
    /* file not present yet */
  }
});
